### PR TITLE
ESLint and Prettier integration + Minor lint fix

### PR DESCRIPTION
**Pull request by Michael-Xie**

### CODE REVIEW

**Comment by linyh0207** [comment]
The updated configuration for ESlint and Prettier does not work when I test it out locally with Github Desktop.

**Comment by Michael-Xie** [comment]
What error did you get?

**Comment by linyh0207** [comment]
I got many linting errors and warnings as I opened then saved files.

**Comment by Michael-Xie** [comment]
Hmm you have a screenshot of the errors and warnings? And the eslintrc file? 

When you checked out the pull request, did you add any code before commiting?

**Comment by linyh0207** [comment]
I basically tested out your pull request (branch) locally. Let's take a look at this tgt in tmr's meeting or later tonight if you have time.

**Pull request merged**
